Feature/143412453/limit-number-of-invites
andela/reactors-cards-for-humanity pull request #18
Opened 2017-04-25 13:46 UTC by andela-wmumbi

#### What does this PR do?
Users should be able to invite people to their game up to a maximum of 11 other people, so no game can exceed 12 people in total and must have at least 3 players.
 #### Description of Task to be completed?
bower install sweetalert
 #### How should this be manually tested?
run gulp
 #### What are the relevant pivotal tracker stories?
#143412453
 #### Screenshots (if appropriate)
<img width="1280" alt="game" src="https://cloud.githubusercontent.com/assets/27006277/25388460/9b0d014a-29d6-11e7-9675-dd05df30d43c.png">

2017-04-26 08:18 UTC, gangachris commented
Few Points:

- Reslove merge conflicts
- Check PR naming convention here from the wiki https://github.com/andela/reactors-cards-for-humanity/wiki/PR-naming-and-Description
- You only have the less than three people screenshot, add the more than 11 players one.

2017-04-26 08:35 UTC, gangachris commented on app/views/includes/foot.jade
> +//script(type='text/javascript', src='/lib/angular-toastr/dist/angular-toastr.min.js')
minor: delete this line, since it's may never be used

2017-04-26 08:35 UTC, gangachris commented on bower.json
> +    "angular-animate": "^1.6.4"
minor: delete these dependencies. We are not using them

2017-04-26 08:35 UTC, gangachris commented on package.json
> +    "install": "^0.8.8",
what does this do?

2017-04-26 08:35 UTC, gangachris commented on package.json
> +    "sweetalert": "^1.1.3",
I'm not sure how your sweetalert worked. And how it got to the `public/lib` folder. This should be in `bower.json` or maybe just get it as a CDN https://cdnjs.com/libraries/sweetalert

2017-04-26 08:35 UTC, gangachris commented on package.json
> +    "gulp": "^3.9.1",
You probably need to rebase you branch. Gulp was already installed by @Mercy-Muchai

2017-04-26 08:35 UTC, gangachris commented on package.json
> +    "nodemon": "^1.11.0",
ditto ☝️

2017-04-27 11:54 UTC, LWanjiru requested changes
Needs linting, relevant comments and changes on a file that seems to not belong in the codebase

2017-04-27 11:54 UTC, LWanjiru commented on config/express.js
> +  app.use(bodyParser.urlencoded({extended: true}));
There should be space between the starting curly brace and the words and also the closing one i.e.  ...({ extended: true }).

2017-04-27 11:54 UTC, LWanjiru commented on config/socket/game.js
>    // console.log(self.gameID,self.state);
This comment doesn't seem to be relevant to the code. It should be removed

2017-04-27 11:54 UTC, LWanjiru commented on config/socket/game.js
>    // console.log(self.gameID,self.state);
This comment doesn't seem to be relevant to the code. It should be removed

2017-04-27 11:54 UTC, LWanjiru commented on config/socket/game.js
>    // TODO: do stuff
What does this comment mean?

2017-04-27 11:54 UTC, LWanjiru commented on config/socket/game.js
>      // TODO: Do something?
What does this comment mean?

2017-04-27 11:54 UTC, LWanjiru commented on config/socket/socket.js
>            return err; // Hopefully this never happens.
What does this comment mean?

2017-04-27 11:54 UTC, LWanjiru commented on public/js/controllers/game.js
> +  $scope.showFirst = function (card) {
Use arrow function here.

2017-04-27 11:54 UTC, LWanjiru commented on public/js/controllers/game.js
> +  $scope.secondAnswer = function ($index) {
Use arrow function here.

2017-04-27 11:54 UTC, LWanjiru commented on public/js/controllers/game.js
> +  $scope.firstAnswer = function ($index) {
Use arrow function here.

2017-04-27 11:54 UTC, LWanjiru commented on public/js/controllers/game.js
> +  $scope.cardIsSecondSelected = function (card) {
use arrow function

2017-04-27 11:54 UTC, LWanjiru commented on public/js/controllers/game.js
> +  $scope.cardIsFirstSelected = function (card) {
Use arrow function here.

2017-04-27 11:54 UTC, LWanjiru commented on public/js/controllers/game.js
> +  $scope.pickCard = function (card) {
Use arrow function here.

2017-04-27 11:54 UTC, LWanjiru commented on public/js/controllers/game.js
> +.controller('GameController', ['$scope', 'game', '$timeout', '$location', 'MakeAWishFactsService', '$dialog', function ($scope, game, $timeout, $location, MakeAWishFactsService, $dialog) {
function... ES6

2017-04-27 11:54 UTC, LWanjiru commented on public/js/controllers/game.js
> +  $scope.sendPickedCards = function () {
This will raise an error when listing

2017-04-27 11:54 UTC, LWanjiru commented on public/js/controllers/game.js
> +  $scope.showSecond = function (card) {
consider using arrow function.

2017-04-27 11:54 UTC, LWanjiru commented on public/js/controllers/game.js
> +  $scope.isCzar = function () {
unnamed function

2017-04-27 11:54 UTC, LWanjiru commented on public/js/controllers/game.js
> +  $scope.isPlayer = function ($index) {
use arrow function

2017-04-27 11:54 UTC, LWanjiru commented on public/js/controllers/game.js
> +  $scope.pickWinning = function (winningSet) {
Use arrow function

2017-04-27 11:54 UTC, LWanjiru commented on testing.js
> + * A simple React component
This comment is not relevant to the code

2017-04-27 11:54 UTC, LWanjiru commented on testing.js
> +// What is happening here?
This comment is not relevant to the code

2017-04-27 11:54 UTC, LWanjiru commented on testing.js
> +    // What does the state object do?
This comment is not relevant to the code

2017-04-27 11:54 UTC, LWanjiru commented on testing.js
> +class Why extends React.Component {
Is this file part of the CFH codebase? It is on react and the codebase uses angular...

2017-05-02 07:22 UTC, gangachris commented
fix linting and merge conflicts then reopen

2017-05-02 07:22 UTC, closed without merging